<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inp_zipcode</name>
   <tag></tag>
   <elementGuidId>065c6fbb-b19d-48e7-a2fe-c702518e5690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[@name='username']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address.zipCode']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
