<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inp_address</name>
   <tag></tag>
   <elementGuidId>74a3df4c-b554-4f62-8d53-7964b3720ed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//input[@id='customer.address.street']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address.street']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
