<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>str_error_msg</name>
   <tag></tag>
   <elementGuidId>b697c76e-bc91-4339-a7b0-9799e1079765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[@name='username']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='firstName.errors']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
